### ISSUE TITLE
ENHANCEMENT: What if we have only 1 api call then we will just conditionally render in the frontend?

### ISSUE THREAD

**Issue by emmarcaber** [markpenales/jpcs-cspc-bycit#1]
I have seen that you have a dynamic dropdown for programs and sections that will call an API route based on the user's input. I think that this will cause too much network traffic since what if there were multiple users signing up simultaneously? Possible effect will be that the server will be having hard time handling the requests requested by each user or client.

*I suggest that we only have __one (1) API call__ that will fetch all the program and sections available. Then, we will just conditionally render in the frontend*. Having this approach will have a positive effect on reducing the network traffic generated due to dynamic dropdown.

**Comment by markpenales** [comment]
Already solved in latest pushes
